-- 챗봇 전용 엔터프라이즈 격리 데이터베이스 (Target Isolated PostgreSQL Database) 스키마

CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS customer_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    card_number VARCHAR(50) NOT NULL,
    ssn VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    order_id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    total_amount VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL
);

-- RAG 벡터 지식베이스 도큐먼트 테이블 (사내 공개 규정집 및 대외비 기밀 문서)
CREATE TABLE IF NOT EXISTS rag_knowledge_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    category VARCHAR(50) NOT NULL,
    security_level VARCHAR(20) NOT NULL, -- 'PUBLIC', 'CONFIDENTIAL'
    content TEXT NOT NULL
);
